### ISSUE TITLE
Void-function error

### ISSUE THREAD

**Issue by mclearc** [lordpretzel/mu4e-views#28]
I get the following whenever I open an email with the mu4e-view function:

```emacs-lisp
Error during redisplay: (eval (when xwidget-webkit--loading-p (let ((session (xwidget-webkit-current-session))) (format " [%d%%%%]" (* 100 (xwidget-webkit-estimated-load-progress session)))))) signaled (void-function xwidget-webkit-estimated-load-progress)
```

Here's my xwidgets setup:

```emacs-lisp
(use-package xwidget
  :straight (:type built-in)
  :defer 1
  :config
  (require 'xwidget))
```

I'm on GNU Emacs 29.0.50 (build 1, aarch64-apple-darwin21.3.0, NS appkit-2113.30 Version 12.2.1 (Build 21D62), git sha1 d64a1f7251). 

This might be an upstream bug similar to #18, but I'm not sure so I figured I'd start a new thread.

**Comment by lordpretzel** [comment]
Hi,

you are on mac, right? I also have this problem with `29.0.50`. I've did a quick check and it seems that `xwidget-webkit-estimated-load-progress` is a C function that is available in emacs master since late December. This is unrelated to mu4e views, but probably a problem in the mac patch that uses webkit for xwidgets in certain mac os x build. Did you install from emacs-plus or similar. We should report this bug there.

**Comment by lordpretzel** [comment]
in the meanwhile,

``` emacs-lisp
(defun xwidget-webkit-estimated-load-progress (session)
  1.0)
```

is a workaround

**Comment by mclearc** [comment]
I actually build emacs from source (edit: but yes, on macos 12.2). So I should figure out if there is something wonky in my build process. But your suggested workaround does the trick -- apologies for the noise and appreciate the quick reply (and great package)!

**Comment by lordpretzel** [comment]
thanks! 
Most likely this is caused by the mac build of xwidget which replaces the gtk version with webkit and this function has not been implemented yet, but since it seems that this just measuring loading progress, the workaround should not cause any problems (I hope).
